name: mun_bot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The folulowing defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+27

environment:
  sdk: ">=2.14.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  percent_indicator: ^3.3.0-nullsafety.1
  #syncfusion_flutter_charts: ^19.1.54 # adding for graph by Chanakan(artzaza7)
  qr_code_scanner: ^0.5.2 # adding for qrCode by Theeraphat(R2BT)
  google_fonts: 2.2.0
  image_picker: ^0.8.4+1
  path_provider: ^2.0.4
  photo_view: ^0.12.0
  #scan: 1.4.0
  progress_dialog_null_safe: ^1.0.7
  flutter_switch: ^0.3.2
  splashscreen: ^1.3.5
  expandable_text: ^2.3.0
  #google_sign_in: ^5.3.1
  #firebase_auth: 2.0.0
  #firebase_core: ^1.12.0
  #flutter_qr_reader: ^1.0.5
  #qrscan: ^0.3.3
  scan: ^1.6.0


  multi_select_flutter: 4.1.1
#  url_launcher: ^6.1.2
  jwt_decode: ^0.3.1
  shared_preferences: 2.0.15
  jwt_decoder: ^2.0.1
  flutter_toastr: ^1.0.3  
  animated_toggle_switch: ^0.5.2
  flutter_custom_tabs: ^1.0.4
  permission_handler: ^8.1.5
  geolocator: ^7.0.2
  dio: ^4.0.6
  http: ^0.13.3
  basic_utils: ^3.0.0
  location: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  intl: ^0.17.0
  convex_bottom_bar: ^3.1.0+1
  getwidget: ^3.0.1
  dropdown_search: ^3.0.1
  cupertino_icons: ^1.0.5
  json_annotation: ^4.6.0
  #flutster: ^1.0.0
  month_year_picker: ^0.1.0+3
  flutter_lints: ^1.0.0
  fl_chart: ^0.51.0
  camera: ^0.9.4+2
  gallery_saver: ^2.3.2
  #material_floating_search_bar: ^0.3.7
  provider: ^6.0.3
  table_calendar: ^3.0.6
  google_maps_flutter: ^2.1.5
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  dio: ^4.0.6
  flutter_staggered_animations: ^1.0.0
  #filter_list: ^1.0.2
  #flutter_native_splash: ^2.0.1+1
  #splashscreen: ^1.3.5
  number_inc_dec: ^0.8.0
  localization: ^2.1.0
  #flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.5
  datetime_picker_formfield: ^2.0.1
  pie_chart: ^5.3.2
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.1.0
  flutter_speed_dial: ^5.0.0+1
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0
  badges: ^2.0.2
  #sign_in_with_apple: ^3.3.0
  auth_buttons: ^2.0.4
  crypto: ^3.0.1
  #webview_flutter: ^3.0.4
  hexcolor: ^2.0.3
  flutter_inappwebview: ^5.6.0
  #animations: ^2.0.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
  #  - assets/certificate/
    - assets/lang/
    - assets/images/Menupic/
